### ISSUE TITLE
Layout overflows when messing with TextField(s)

### ISSUE THREAD

**Issue by firatcetiner** [sagarshende23/Simple_calculator_flutter#1]
Hi, loved your work.

Just noticed a tiny bug. Since the "Result" and "Input" fields are just TextField(s), it gives an error when an action is taken (e.g. long press on TextField).

![Screenshot_2019-07-09-23-06-34-635_com example stupid_calculator](https://user-images.githubusercontent.com/23283730/60919839-633db900-a29f-11e9-852d-2687359fcc35.png)

Fixing it by setting the `enabled` property of TextField to `false`.

**Comment by sagarshende23** [comment]
Oh, Thanks for Issue...
Yeah Result is the Textfield But I am not getting an error on my Device (long press on TextField)
Because every Device Has Different Size
ok, I am going to solve it..
Solution => If Any Body Longpress on Textfield We can give him Error or Something Snackbar Or Disable it Textfield..
